/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.PreparaConexao;
import fatec.poo.control.DaoHotel;
import fatec.poo.control.DaoReserva;
import fatec.poo.model.Data;
import fatec.poo.model.Hotel;
import fatec.poo.model.Reserva;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * @author Joao Reche e Leonardo Cordeiro
 */
public class GuiReserva extends javax.swing.JFrame {

    /**
     * Creates new form GuiReserva
     */
    public GuiReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodHotel = new javax.swing.JLabel();
        lblCodReserva = new javax.swing.JLabel();
        txtCodReserva = new javax.swing.JTextField();
        txtCodHotel = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblNomeHosp = new javax.swing.JLabel();
        lblDtEntrada = new javax.swing.JLabel();
        txtNomeHosp = new javax.swing.JTextField();
        txtDtEntrada = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDtSaida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDtSaida = new javax.swing.JTextField();
        lblDiasHosp = new javax.swing.JLabel();
        lblValorHosped = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnConsultarHotel = new javax.swing.JButton();
        btnConsultarReserva = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        lblNomeHotel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCodHotel.setText("Código Hotel");

        lblCodReserva.setText("Código Reserva");

        txtCodReserva.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Check In"));

        lblNomeHosp.setText("Nome Hóspede");

        lblDtEntrada.setText("Data de Entrada (dd/mm/aaaa)");

        txtNomeHosp.setEnabled(false);

        txtDtEntrada.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblDtEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblNomeHosp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeHosp))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeHosp)
                    .addComponent(txtNomeHosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtEntrada)
                    .addComponent(txtDtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Check Out"));

        lblDtSaida.setText("Data Saída (dd/mm/aaaa)");

        jLabel6.setText("Qtde. de Dias Hospedados");

        jLabel7.setText("Valor Hospedagem");

        txtDtSaida.setEnabled(false);

        lblDiasHosp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblValorHosped.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDtSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiasHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorHosped, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtSaida)
                    .addComponent(txtDtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(lblDiasHosp, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(lblValorHosped, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDiasHosp, lblValorHosped, txtDtSaida});

        btnCheckOut.setText("Check Out");
        btnCheckOut.setEnabled(false);
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultarHotel.setText("Consultar Hotel");
        btnConsultarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHotelActionPerformed(evt);
            }
        });

        btnConsultarReserva.setText("Consultar Reserva");
        btnConsultarReserva.setEnabled(false);
        btnConsultarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarReservaActionPerformed(evt);
            }
        });

        btnCheckIn.setText("Check In");
        btnCheckIn.setEnabled(false);
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        lblNomeHotel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultarHotel)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarReserva)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckIn)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckOut)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodReserva)
                            .addComponent(lblCodHotel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCodReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCodHotel, txtCodReserva});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeHotel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCodHotel)
                                .addComponent(txtCodHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCodReserva)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarHotel)
                    .addComponent(btnConsultarReserva)
                    .addComponent(btnCheckIn)
                    .addComponent(btnCheckOut)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblNomeHotel, txtCodHotel});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose(); // Fecha a GUI
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        prepCon = new PreparaConexao("Jvz", "joao2014");
        prepCon.setDriver("oracle.jdbc.driver.OracleDriver");
        prepCon.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        
        daoHotel = new DaoHotel(prepCon.abrirConexao());
        daoReserva = new DaoReserva(prepCon.abrirConexao());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        prepCon.fecharConexao();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHotelActionPerformed
        // Limpa todos os resquicios de uma operacao anterior
        txtCodReserva.setText(null);
        txtNomeHosp.setText(null);
        txtDtEntrada.setText(null);
        txtDtSaida.setText(null);
        lblDiasHosp.setText(null);
        lblValorHosped.setText(null);

        hotel = daoHotel.consultar(Integer.parseInt(txtCodHotel.getText()));

        if (hotel == null) {
            JOptionPane.showMessageDialog(this, "Hotel não cadastrado",
                    "Alerta", JOptionPane.WARNING_MESSAGE);
            txtCodHotel.setText(null);
            txtCodHotel.requestFocus();
        } else {
            lblNomeHotel.setText(hotel.getNome());
            
            txtCodHotel.setEnabled(false);
            txtCodReserva.setEnabled(true);
            txtCodReserva.requestFocus();
            
            btnConsultarHotel.setEnabled(false);
            btnConsultarReserva.setEnabled(true);
        }
    }//GEN-LAST:event_btnConsultarHotelActionPerformed

    private void btnConsultarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarReservaActionPerformed
        reserva = daoReserva.consultar(Integer.parseInt(txtCodReserva.getText()));

        if (reserva == null) {
            txtCodReserva.setEnabled(false);
            txtNomeHosp.setEnabled(true);
            txtDtEntrada.setEnabled(true);
            txtNomeHosp.requestFocus();
            
            btnConsultarReserva.setEnabled(false);
            btnCheckIn.setEnabled(true);
        } else {
            txtNomeHosp.setText(reserva.getNomeHosp());
            txtDtEntrada.setText(reserva.getDataEntrada().obterData());
            
            txtCodReserva.setEnabled(false);
            txtDtSaida.setEnabled(true);
            txtDtSaida.requestFocus();
            btnConsultarReserva.setEnabled(false);
            
            btnCheckIn.setEnabled(false);
            btnCheckOut.setEnabled(true);

            // Restaura/Efetiva a ligacao de reserva com hotel
            reserva.setHotel(hotel);
        }
    }//GEN-LAST:event_btnConsultarReservaActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // Pega a data de entrada que esta salva como texto
        String dataEntradaString = txtDtEntrada.getText();
        
        // Quebra o texto onde tem a "/" gerando um vetor com 3 posicoes
        String[] partesData = dataEntradaString.split("/");

        // Converte os pedaços de texto para inteiros
        int dia = Integer.parseInt(partesData[0]);
        int mes = Integer.parseInt(partesData[1]);
        int ano = Integer.parseInt(partesData[2]);

        // Instancia Data
        Data dtEntrada = new Data(dia, mes, ano);

        // Instancia Reserva
        reserva = new Reserva(Integer.parseInt(txtCodReserva.getText()),
                txtNomeHosp.getText(), dtEntrada);

        // Faz a ligacao bidirecional
        hotel.addReserva(reserva);

        daoReserva.inserir(reserva);

        txtCodHotel.setText(null);
        lblNomeHotel.setText(null);
        txtCodReserva.setText(null);
        txtNomeHosp.setText(null);
        txtDtEntrada.setText(null);

        txtNomeHosp.setEnabled(false);
        txtDtEntrada.setEnabled(false);
        txtCodHotel.setEnabled(true);
        txtCodHotel.requestFocus();

        btnConsultarHotel.setEnabled(true);
        btnCheckIn.setEnabled(false);
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        DecimalFormat df = new DecimalFormat("#,##0.00");

        // Pega a data de entrada que esta salva como texto
        String dataSaidaString = txtDtSaida.getText();
        
        // Quebra o texto onde tem a "/" gerando um vetor com 3 posicoes
        String[] partesData = dataSaidaString.split("/");

        // Converte os pedaços de texto para inteiros
        int dia = Integer.parseInt(partesData[0]);
        int mes = Integer.parseInt(partesData[1]);
        int ano = Integer.parseInt(partesData[2]);

        // Instancia Data
        Data dtSaida = new Data(dia, mes, ano);

        // Calcula e exibe a quantidade de dias hospedados
        lblDiasHosp.setText(String.valueOf(dtSaida.subtrairDatas(reserva.getDataEntrada())));

        // Encerra a reserva e calcula o valor a pagar
        double valorPagar = reserva.encerrarReserva(dtSaida);

        lblValorHosped.setText(" R$ " + String.valueOf(df.format(valorPagar)));

        // Soma o valor recebido ao total de faturamento do hotel
        hotel.addValorHospedagem(valorPagar);

        daoReserva.alterar(reserva);
        daoHotel.alterar(hotel);

        btnCheckOut.setEnabled(false);
        txtDtSaida.setEnabled(false);
        txtCodHotel.setEnabled(true);
        txtCodHotel.setText(null);
        txtCodHotel.requestFocus();

        btnConsultarHotel.setEnabled(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnConsultarHotel;
    private javax.swing.JButton btnConsultarReserva;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCodHotel;
    private javax.swing.JLabel lblCodReserva;
    private javax.swing.JLabel lblDiasHosp;
    private javax.swing.JLabel lblDtEntrada;
    private javax.swing.JLabel lblDtSaida;
    private javax.swing.JLabel lblNomeHosp;
    private javax.swing.JLabel lblNomeHotel;
    private javax.swing.JLabel lblValorHosped;
    private javax.swing.JTextField txtCodHotel;
    private javax.swing.JTextField txtCodReserva;
    private javax.swing.JTextField txtDtEntrada;
    private javax.swing.JTextField txtDtSaida;
    private javax.swing.JTextField txtNomeHosp;
    // End of variables declaration//GEN-END:variables
    private PreparaConexao prepCon;
    private DaoHotel daoHotel;
    private DaoReserva daoReserva;
    private Hotel hotel;
    private Reserva reserva;
}
